spring:
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@192.168.1.207:1521/razor
    password: dpc
    username: dpc
mybatis:
  mapper-locations: classpath:mapper/*.xml
server:
  port: 8888